site_name: CommonSENSES Project
site_url: https://kriishahate.github.io/CommonSENSES/
repo_url: https://github.com/kriishahate/CommonSENSES
theme:
  name: material
nav:
  - Home: index.md
plugins:
  - search
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      format: "%B %d, %Y"
      prefix: "Last updated: "
